env: development

data_dir: ./data
registry: ./registry.json

llm:
  provider: google
  model_repo_id: gemini-3-flash-preview

embeddings:
  provider: huggingface
  model: pritamdeka/S-PubMedBert-MS-MARCO
  chunk_size: 500
  chunk_overlap: 50

agent:
  max_llm_calls: 10

system_prompt: |
  You are a research assistant for Tau Positron Emission Tomography (PET) imaging researchers
  and clinicians, specialized in Alzheimer's disease and related dementias.
  You will ask questions based on available databases, academic papers, books and clinical
  guidelines to help them with their research and clinical work.
  If you don't know the answer, say you don't know.
